#!/usr/bin/env python3
"""Regenerate nix/cbind-deps.nix from the pinned Delivery dependency graph."""

import re
import subprocess
import sys
import urllib.request

DELIVERY_REV = "a00aba618890397ef40d1a16b22b094d8afd0a62"
DELIVERY_URL = "https://github.com/logos-messaging/logos-delivery.git"
DELIVERY_DEPS_URL = (
    "https://raw.githubusercontent.com/logos-messaging/logos-delivery/"
    f"{DELIVERY_REV}/nix/deps.nix"
)

FETCHGIT = re.compile(
    r"(\w+)\s*=\s*pkgs\.fetchgit\s*\{\s*"
    r'url\s*=\s*"([^"]+)";\s*'
    r'rev\s*=\s*"([^"]+)";\s*'
    r'sha256\s*=\s*"([^"]+)";',
    re.DOTALL,
)


def prefetch(url: str, rev: str) -> str:
    result = subprocess.run(
        [
            "nix-prefetch-git",
            "--url", url,
            "--rev", rev,
            "--fetch-submodules",
            "--quiet",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    match = re.search(r'"sha256"\s*:\s*"([^"]+)"', result.stdout)
    if match is None:
        raise RuntimeError(f"no sha256 in output for {url}@{rev}")
    return match.group(1)


def main() -> int:
    with urllib.request.urlopen(DELIVERY_DEPS_URL) as response:
        source = response.read().decode()
    deps = {
        match.group(1): (match.group(2), match.group(3), match.group(4))
        for match in FETCHGIT.finditer(source)
    }
    deps["logos_delivery"] = (
        DELIVERY_URL,
        DELIVERY_REV,
        prefetch(DELIVERY_URL, DELIVERY_REV),
    )

    out = [
        "# AUTOGENERATED by tools/regen-cbind-deps.py",
        "{ pkgs }:",
        "",
        "{",
    ]
    for name in sorted(deps):
        url, rev, sha = deps[name]
        out.extend([
            f"  {name} = pkgs.fetchgit {{",
            f'    url = "{url}";',
            f'    rev = "{rev}";',
            f'    sha256 = "{sha}";',
            "    fetchSubmodules = true;",
            "  };",
            "",
        ])
    out.append("}")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
