#!/usr/bin/env python3
"""Regenerate nix/cbind-deps.nix from nimble.lock."""

import re
import subprocess
import sys
import json
from pathlib import Path

FETCHGIT = re.compile(
    r"(\w+)\s*=\s*pkgs\.fetchgit\s*\{\s*"
    r'url\s*=\s*"([^"]+)";\s*'
    r'rev\s*=\s*"([^"]+)";\s*'
    r'sha256\s*=\s*"([^"]+)";',
    re.DOTALL,
)


def prefetch(url: str, rev: str) -> str:
    result = subprocess.run(
        [
            "nix-prefetch-git",
            "--url", url,
            "--rev", rev,
            "--fetch-submodules",
            "--quiet",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    match = re.search(r'"sha256"\s*:\s*"([^"]+)"', result.stdout)
    if match is None:
        raise RuntimeError(f"no sha256 in output for {url}@{rev}")
    return match.group(1)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    lock = json.loads((root / "nimble.lock").read_text())
    previous = {
        m.group(1): (m.group(2), m.group(3), m.group(4))
        for m in FETCHGIT.finditer((root / "nix/cbind-deps.nix").read_text())
    }
    deps = {}
    for name, package in lock["packages"].items():
        if name == "nim":
            continue
        url, rev = package["url"], package["vcsRevision"]
        cached = previous.get(name)
        sha = cached[2] if cached and cached[:2] == (url, rev) else prefetch(url, rev)
        deps[name] = (url, rev, sha)

    out = [
        "# AUTOGENERATED by tools/regen-cbind-deps.py",
        "{ pkgs }:",
        "",
        "{",
    ]
    for name in sorted(deps):
        url, rev, sha = deps[name]
        out.extend([
            f"  {name} = pkgs.fetchgit {{",
            f'    url = "{url}";',
            f'    rev = "{rev}";',
            f'    sha256 = "{sha}";',
            "    fetchSubmodules = true;",
            "  };",
            "",
        ])
    out.append("}")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
